language: node_js
node_js:
- '12'
cache: npm
before_install:
- npm install
script:
- node_modules/.bin/jshint
- node_modules/.bin/twly
deploy:
  provider: heroku
  api_key:
    secure: LmKj3fvyxMn32umKj52wqHaNzOquxmUhR4dei/vd0iRe0GYAmI4AZBBZyAhl8RVYqSEOW977mzg3jroszdWlNbl+jyAjXxhJpFn786TipEqqPREL5zu7jtlX8X6LrHR3O7XW+vtlH+iAB0tqZfV68O8/F4oAZvUONAMD5GRL5z6G+e92BSyGYgFsh8Q7SwZSkz12m5uH+vHCGXJ62SnW2pc95Ryjw3h6lyeFUg4kwPGBobAwiBgWZHOJs9jGu4NOGK6AKu9XefXqgG39PFw5/FENLlXomClCQBP6ZNP8i0jPCE6Hs15a9frIMN2be0+M7nnR2L0/SQDQBov9jqCKs6rMxD3GrFuxWLzrPBsolpLfgDttbpLL7CLq/bxl5sXjOZvEdBnVCspSD3wIGMCAdTyuwoxMRZbm7AEt0+9TsktOR67GQIkQeTuiJJPAK/7r6ZtLQiJe6EqGKvVNVi5nWpAKQt29BTY3ProrB2MDCFLdrlSaDC3pr+LCYnOLVR6CySBih4BdPhmQ+hG4AZ2wwMFbGKPiSNufawN7GgX35IaY8Cew+YddqXRtTXJdg56Li3D6rq/GW18r+xSmJo1iu+QYG8dZCCPZskA9rmVbZ8rmXu5P5kQpC5JsGzGfHXEz0DzUHljUwBxNaeUmN3+GxpNwymhDSGFgvX2dnVTsXdU=
  app: ippsi-evaluation